- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yml
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi we are learning {{Course}} trainer {{Trainer}} Duration {{Duration}}"

