- name: data types
  hosts: localhost 
  vars:
    Course: DevOps with AWS 
    Tools:
    - Linux
    - Shell
    - Ansible 
    Experience: 
      DevOps: 3
      AWS: 2
      Docker: 1
    RealProject: true 
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"