- name: install packages
  hosts: web 
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      msg: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx   
    - postfix